<template>
    <div class="exhibitionDetails">
        <div class="exhColumns">
            <div class="desc">
                <h3>Životopis</h3>
                Nenad Opačić rođen je 1949. godine u Varaždinu. Godine 1972.  završio je ALU u Zagrebu u klasi profesora Raula Goldonija, a  predavali su mu i profesori: Ljubo Ivančić, Ferdinand Kulmer,  Ivo Šebalj, Matko Peić i dr. Od 1972. do 1975. godine suradnik  je majstorske radionice profesora Krste Hegedušića, a od 1976.  do 1991. godine voditelj je Galerije Karas i galerije HDLU-a  Zagreb. Nenad Opačić ostvario je preko devedeset samostalnih  izložbi i sudjelovao na više od dvjesto skupnih izložbi u zemlji i  inozemstvu. Sada radi kao samostalni umjetnik. U Varaždinu, u  svojoj otvorenoj galeriji i atelijeru, organizira susrete; promocije  muzičara, pjesnika i filozofa, uz uvijek novi postav skulptura i slika,  kako u eksterijeru, tako i u interijeru. Izdavanjem monografije,  2009. godine, autora Zdenka Rusa i Đuke Opačića, umjetnik  okrunjuje svoj 50 godina stvaralački opus kroz 366 odabranih  reprodukcija. Od 2011. do 2022. je (s kraćim prekidima) bio  predsjednik HDLU-a Varaždin. Za svoj aktivan rad na likovnoj sceni  dobio je brojne nagrade i priznanja, a posebno se ističe Nagrada za  životno djelo Grada Varaždina, koja mu je dodijeljena 2022. godine.
            </div>
            <div class="desc">
                Nenad Opačić rođen je 1949. godine u Varaždinu. Godine 1972.  završio je ALU u Zagrebu u klasi profesora Raula Goldonija, a  predavali su mu i profesori: Ljubo Ivančić, Ferdinand Kulmer,  Ivo Šebalj, Matko Peić i dr. Od 1972. do 1975. godine suradnik  je majstorske radionice profesora Krste Hegedušića, a od 1976.  do 1991. godine voditelj je Galerije Karas i galerije HDLU-a  Zagreb. Nenad Opačić ostvario je preko devedeset samostalnih  izložbi i sudjelovao na više od dvjesto skupnih izložbi u zemlji i  inozemstvu. Sada radi kao samostalni umjetnik. U Varaždinu, u  svojoj otvorenoj galeriji i atelijeru, organizira susrete; promocije  muzičara, pjesnika i filozofa, uz uvijek novi postav skulptura i slika,  kako u eksterijeru, tako i u interijeru. Izdavanjem monografije,  2009. godine, autora Zdenka Rusa i Đuke Opačića, umjetnik  okrunjuje svoj 50 godina stvaralački opus kroz 366 odabranih  reprodukcija. Od 2011. do 2022. je (s kraćim prekidima) bio  predsjednik HDLU-a Varaždin. Za svoj aktivan rad na likovnoj sceni  dobio je brojne nagrade i priznanja, a posebno se ističe Nagrada za  životno djelo Grada Varaždina, koja mu je dodijeljena 2022. godine.
            </div>
            <div class="desc">
                Nenad Opačić rođen je 1949. godine u Varaždinu. Godine 1972.  završio je ALU u Zagrebu u klasi profesora Raula Goldonija, a  predavali su mu i profesori: Ljubo Ivančić, Ferdinand Kulmer,  Ivo Šebalj, Matko Peić i dr. Od 1972. do 1975. godine suradnik  je majstorske radionice profesora Krste Hegedušića, a od 1976.  do 1991. godine voditelj je Galerije Karas i galerije HDLU-a  Zagreb. Nenad Opačić ostvario je preko devedeset samostalnih  izložbi i sudjelovao na više od dvjesto skupnih izložbi u zemlji i  inozemstvu. Sada radi kao samostalni umjetnik. U Varaždinu, u  svojoj otvorenoj galeriji i atelijeru, organizira susrete; promocije  muzičara, pjesnika i filozofa, uz uvijek novi postav skulptura i slika,  kako u eksterijeru, tako i u interijeru. Izdavanjem monografije,  2009. godine, autora Zdenka Rusa i Đuke Opačića, umjetnik  okrunjuje svoj 50 godina stvaralački opus kroz 366 odabranih  reprodukcija. Od 2011. do 2022. je (s kraćim prekidima) bio  predsjednik HDLU-a Varaždin. Za svoj aktivan rad na likovnoj sceni  dobio je brojne nagrade i priznanja, a posebno se ističe Nagrada za  životno djelo Grada Varaždina, koja mu je dodijeljena 2022. godine.
            </div>
            <div class="desc">
                Nenad Opačić rođen je 1949. godine u Varaždinu. Godine 1972.  završio je ALU u Zagrebu u klasi profesora Raula Goldonija, a  predavali su mu i profesori: Ljubo Ivančić, Ferdinand Kulmer,  Ivo Šebalj, Matko Peić i dr. Od 1972. do 1975. godine suradnik  je majstorske radionice profesora Krste Hegedušića, a od 1976.  do 1991. godine voditelj je Galerije Karas i galerije HDLU-a  Zagreb. Nenad Opačić ostvario je preko devedeset samostalnih  izložbi i sudjelovao na više od dvjesto skupnih izložbi u zemlji i  inozemstvu. Sada radi kao samostalni umjetnik. U Varaždinu, u  svojoj otvorenoj galeriji i atelijeru, organizira susrete; promocije  muzičara, pjesnika i filozofa, uz uvijek novi postav skulptura i slika,  kako u eksterijeru, tako i u interijeru. Izdavanjem monografije,  2009. godine, autora Zdenka Rusa i Đuke Opačića, umjetnik  okrunjuje svoj 50 godina stvaralački opus kroz 366 odabranih  reprodukcija. Od 2011. do 2022. je (s kraćim prekidima) bio  predsjednik HDLU-a Varaždin. Za svoj aktivan rad na likovnoj sceni  dobio je brojne nagrade i priznanja, a posebno se ističe Nagrada za  životno djelo Grada Varaždina, koja mu je dodijeljena 2022. godine.
            </div>
        </div>
        <div class="imgContainer">
            <img src="@/assets/img/exh2.png" alt="">
        </div>
    </div>
</template>